extends RefCounted

func run(support: TestSupport) -> void:
	support.expect(AnimationStateRules.STATES == ["idle", "move", "attack", "hit", "death"], "animation states must use one normalized vocabulary")
	support.expect(AnimationStateRules.resolve(true, true, true, true) == "death", "death must have highest presentation priority")
	support.expect(AnimationStateRules.resolve(false, true, true, true) == "hit", "hit must override attack and locomotion")
	support.expect(AnimationStateRules.resolve(false, false, true, true) == "attack", "attack must override locomotion")
	support.expect(AnimationStateRules.resolve(false, false, false, true) == "move", "moving actors must resolve move")
	support.expect(AnimationStateRules.resolve(false, false, false, false) == "idle", "stationary actors must resolve idle")
	support.expect(AnimationStateRules.frame_index(0.3, 5.0, 2) == 1, "looping frame selection must be deterministic")
	support.expect(AnimationStateRules.frame_index(2.0, 5.0, 2, false) == 1, "one-shot frame selection must clamp")
	support.expect(AnimationStateRules.loops("idle") and AnimationStateRules.loops("move") and not AnimationStateRules.loops("attack") and not AnimationStateRules.loops("hit") and not AnimationStateRules.loops("death"), "only locomotion clips may loop")
	support.expect(not AnimationStateRules.is_valid("cast"), "unknown animation states must be rejected")
	support.expect(FacingRules.DIRECTIONS.size() == 8 and FacingRules.resolve(Vector2(-1, -1), "south") == "north_west" and FacingRules.resolve(Vector2(1, 1), "north") == "south_east", "hero presentation must resolve all eight authored directions")
	support.expect(VisualAssetLibrary.animation_cell("hero", "move", "north", 1) == Vector2i(3, 4), "production hero lookup must map north movement into the authored Puny row")
	support.expect(VisualAssetLibrary.animation_frame_count("hero", "idle", "south") == 2 and VisualAssetLibrary.animation_frame_count("hero", "move", "south") == 2, "hero locomotion must retain every authored Puny source frame")
	support.expect([VisualAssetLibrary.hero_actor_id_for_weapon("unarmed"), VisualAssetLibrary.hero_actor_id_for_weapon("melee"), VisualAssetLibrary.hero_actor_id_for_weapon("ranged"), VisualAssetLibrary.hero_actor_id_for_weapon("magic")] == ["hero_unarmed", "hero_sword", "hero_bow", "hero_wand"], "canonical equipment types must select distinct hero silhouettes")
	support.expect(VisualAssetLibrary.hero_actor_id_for_weapon("unknown") == "hero_unarmed", "unknown or absent equipment must use the safe unarmed hero")
	support.expect([VisualAssetLibrary.animation_frame_count("hero_unarmed", "attack"), VisualAssetLibrary.animation_frame_count("hero_sword", "attack"), VisualAssetLibrary.animation_frame_count("hero_bow", "attack"), VisualAssetLibrary.animation_frame_count("hero_wand", "attack")] == [2, 4, 4, 4], "equipment families must select complete authored throw, sword, bow, and staff actions")
	support.expect(VisualAssetLibrary.animation_frame_count("hero", "hit") == 1 and VisualAssetLibrary.animation_frame_count("hero", "death") == 5, "hero reactions must use complete authored Puny hurt and death clips")
	support.expect(VisualAssetLibrary.animation_texture("hero_unarmed", "idle").atlas == VisualAssetLibrary.HERO_IDLE_ATLAS and VisualAssetLibrary.animation_texture("hero_sword", "attack").atlas == VisualAssetLibrary.HERO_MELEE_ATLAS and VisualAssetLibrary.animation_texture("hero_bow", "attack").atlas == VisualAssetLibrary.HERO_RANGED_ATLAS and VisualAssetLibrary.animation_texture("hero_wand", "attack").atlas == VisualAssetLibrary.HERO_MAGIC_ATLAS, "hero state and equipment actions must resolve to registered production atlases")
	support.expect(VisualAssetLibrary.animation_cell("slime", "attack", "south", 0) == Vector2i(4, 0), "melee Orc attack tell must map to its authored sword columns")
	support.expect(VisualAssetLibrary.animation_frame_count("ranger", "attack") == 4, "Forest Ranger tell must expose its complete bow action")
	support.expect(VisualAssetLibrary.animation_texture("ranger", "idle", "south", 0, true).atlas == VisualAssetLibrary.PUNY_MAGE_ATLAS, "elite caster must use a distinct authored actor sheet")
	support.expect(VisualAssetLibrary.animation_frame_count("boss", "attack") == 4, "Abyssal Warden must use an authored multi-frame staff clip")
	support.expect(VisualAssetLibrary.vfx_frame_count() == 7 and VisualAssetLibrary.vfx_texture("materialize", 6).region.position == Vector2(384, 384), "v3 VFX must expose a bounded seven-frame materialization sequence")
	support.expect(VisualAssetLibrary.validate_contract().is_empty(), "visual asset library must validate both bootstrap and animation atlases")
	support.expect(ItemIconLibrary.validate_contract().is_empty(), "item icon library must cover every item definition")
	support.expect(ItemIconLibrary.resolved_id("missing_icon") == "fallback", "unknown icon IDs must resolve to the safe fallback")
	support.expect(ItemBaseRegistry.all().all(func(definition: Dictionary) -> bool: return ItemIconLibrary.CELLS.has(String(definition.icon_id))), "all current item bases must reference registered icons")
	var generated := LootGenerator.generate(46051, "icon_contract", 8, "iron_helmet", "rare")
	support.expect(String(generated.icon_id) == "helmet" and ItemIconLibrary.icon_id_for_item(generated) == "helmet", "procedural loot must retain its data-driven icon ID")
	var legacy := EquipmentGenerator.generate(46052)
	support.expect(ItemIconLibrary.icon_id_for_item(legacy) in ["sword", "bow", "wand"], "legacy starter generator must emit a weapon icon ID")
	var icon := ItemIconLibrary.texture("island_shard")
	support.expect(icon.region.size == Vector2(64, 64) and icon.region.position == Vector2(448, 256) and icon.atlas == ItemIconLibrary.ATLAS, "icon regions must stay pixel-perfect 64x64 v3 atlas cells")
	support.expect(ArtAssetValidator.validate_repository().is_empty(), "repository art validation must include new animation and item-icon rasters")
