extends RefCounted

func run(support: TestSupport) -> void:
	support.expect(IslandModifierRegistry.validate().is_empty(), "island modifier registry must validate")
	support.expect(IslandModifierRegistry.all().size() >= 6, "registry must contain the first six gameplay modifiers")
	var categories: Dictionary = {}
	for definition: Dictionary in IslandModifierRegistry.all():
		categories[String(definition.category)] = true
	support.expect(["enemy", "resource", "weather", "reward", "production", "adjacency", "encounter"].all(func(category: String) -> bool: return categories.has(category)), "registry must cover all modifier categories")
	var manager := IslandModifierManager.new()
	var context := {"level": 12, "biome": "forest", "neighbor_count": 1}
	support.expect(manager.sync(["dense_growth", "predatory", "volatile_ore", "arcane_saturation", "nightbound", "overgrown"], context), "six modifier components must attach")
	var effects := manager.effects()
	support.expect(float(effects.get("resource_density_multiplier", 1.0)) > 1.0, "Dense Growth must increase resource density")
	support.expect(int(effects.get("elite_count_bonus", 0)) > 0, "Predatory must add elite pressure")
	support.expect(int(effects.get("ore_explosion_damage", 0)) > 0, "Volatile Ore must add an ore explosion")
	support.expect(float(effects.get("magical_loot_weight", 1.0)) > 1.0, "Arcane Saturation must improve magical loot")
	support.expect(float(effects.get("night_enemy_multiplier", 1.0)) > 1.0 and float(effects.get("night_reward_multiplier", 1.0)) > 1.0, "Nightbound must increase night danger and reward")
	support.expect(int(effects.get("adjacent_growth", 0)) == 1, "Overgrown must project growth to neighbors")
	support.expect(manager.indicators().size() == 6, "every active modifier must expose a UI/visual indicator")
	manager.clear()
	support.expect(manager.active_ids().is_empty() and manager.effects().is_empty(), "modifier clear must detach every component and effect")
	var model := ArchipelagoModel.new(73002)
	model.initialize_default_slots()
	var forest := IslandShardGenerator.generate_for_biome(9301, "forest", 10)
	var swamp := IslandShardGenerator.generate_for_biome(9302, "swamp", 10)
	var volcano := IslandShardGenerator.generate_for_biome(9303, "volcano", 10)
	var frozen := IslandShardGenerator.generate_for_biome(9304, "frozen", 10)
	var graveyard := IslandShardGenerator.generate_for_biome(9305, "graveyard", 10)
	var settlement := IslandShardGenerator.generate_for_biome(9306, "settlement", 10)
	support.expect(model.preview_synergies(swamp, "north_east").is_empty(), "preview without an installed neighbor must be empty")
	model.install("east", forest, IslandRuntimeState.create(forest))
	var spore_preview := model.preview_synergies(swamp, "north_east")
	support.expect(spore_preview.size() == 1 and spore_preview[0].id == "rare_spores", "Forest + Swamp must preview Rare Spores before confirmation")
	support.expect(not String(spore_preview[0].benefit).is_empty() and not String(spore_preview[0].price).is_empty(), "synergy preview must show benefit and price")
	model.install("north_east", swamp, IslandRuntimeState.create(swamp))
	support.expect(model.active_synergies().size() == 1, "installed pair must activate exactly one non-stacking synergy")
	model.install("east", volcano, IslandRuntimeState.create(volcano))
	support.expect(model.active_synergies().is_empty(), "neighbor replacement must remove obsolete synergy")
	model.install("south_east", frozen, IslandRuntimeState.create(frozen))
	support.expect(model.active_synergies()[0].id == "obsidian_front", "Volcano + Frozen must activate Obsidian Front")
	model.remove("south_east")
	model.install("east", graveyard, IslandRuntimeState.create(graveyard))
	support.expect(model.preview_synergies(settlement, "north_east")[0].id == "spirit_siege", "Graveyard + Settlement must preview spirit attacks and energy")
	support.expect(AdjacencySynergyRegistry.validate().is_empty(), "adjacency registry must validate all three tradeoffs")
