extends RefCounted

const QUEST_PATH := "res://game/core/island_story_quest.gd"

func run(support: TestSupport) -> void:
	var Quest: Variant = load(QUEST_PATH)
	support.expect(Quest != null, "island story quest rules must load")
	if Quest == null:
		return
	var forest := IslandShardGenerator.generate_for_biome(99117, "forest", 4)
	var swamp := IslandShardGenerator.generate_for_biome(99118, "swamp", 4)
	var definition: Dictionary = Quest.generate("east", forest)
	support.expect(Quest.validate_definition(definition).is_empty(), "generated island story definition satisfies its full data contract")
	support.expect(definition.biome == "forest" and definition.survey_event == "grove_echo" and definition.warden_name == "Verdant Warden", "forest authors a distinct event and special-enemy identity")
	support.expect(Quest.generate("east", forest) == definition, "same slot and shard reproduce the exact story and reward seeds")
	support.expect((Quest.generate("north_east", forest).reward_seeds as Dictionary) != (definition.reward_seeds as Dictionary), "slot stream separates otherwise identical island rewards")
	var swamp_definition: Dictionary = Quest.generate("east", swamp)
	support.expect(swamp_definition.survey_event == "mire_lantern" and swamp_definition.warden_name == "Sporebound Warden", "swamp authors its own event and Warden identity")
	support.expect(IslandShardGenerator.BIOMES.all(func(biome: String) -> bool: return Quest.validate_definition(Quest.generate("east", IslandShardGenerator.generate_for_biome(12000 + IslandShardGenerator.BIOMES.find(biome), biome, 3))).is_empty()), "all six supported biomes generate valid story definitions")

	var quest: Variant = Quest.new()
	support.expect(quest.status == "locked" and quest.objective_text() == "INSTALL AN ISLAND TO BEGIN TALA'S STORY", "new story starts locked with a useful objective")
	support.expect(quest.bind_island("east", forest) and quest.status == "offered", "binding an installed island creates one offered story")
	support.expect(not quest.bind_island("east", forest) and quest.definition == definition, "resyncing the same island preserves unresolved state")
	support.expect(quest.accept() and quest.status == "active" and quest.stage == 0, "offered story accepts into survey stage")
	support.expect(not quest.accept(), "active story rejects duplicate acceptance")
	support.expect(not bool(quest.record("purge_site", 1, "wrong").accepted), "unrelated gameplay cannot advance the current stage")
	support.expect(bool(quest.record("survey_site", 1, "echo_a").accepted) and quest.progress == 1, "first unique survey site advances exact progress")
	support.expect(not bool(quest.record("survey_site", 1, "echo_a").accepted) and quest.progress == 1, "stable event token prevents duplicate quest credit")
	var surveyed: Dictionary = quest.record("survey_site", 1, "echo_b")
	support.expect(bool(surveyed.stage_advanced) and quest.stage == 1 and quest.branch.is_empty(), "second survey advances to explicit branch choice")
	support.expect(not bool(quest.record("restoration_site", 1, "early").accepted), "branch objectives cannot advance before the player chooses")
	support.expect(not quest.choose_branch("unknown"), "unsupported branch is rejected without mutation")
	support.expect(quest.choose_branch("restoration") and quest.branch == "restoration", "restoration can be selected exactly once")
	support.expect(quest.objective_text().contains("RESTORE"), "restoration branch exposes an unambiguous player-facing objective")
	support.expect(bool(quest.record("restoration_site", 1, "root_a").accepted) and quest.progress == 1, "first restoration site advances")
	support.expect(bool(quest.record("restoration_site", 1, "root_b").stage_advanced) and quest.stage == 2, "restoration target advances to special-Warden stage")
	support.expect(not bool(quest.record("purge_site", 1, "wrong_stage").accepted), "obsolete branch events cannot advance Warden combat")
	support.expect(bool(quest.record("warden_defeated", 1, "warden").completed_now) and quest.status == "completed", "special Warden defeat completes the story")
	var claimed: Dictionary = quest.claim()
	support.expect(bool(claimed.success) and claimed.reward.kind == "island_shard" and int(claimed.reward.expedition_marks) == 2, "restoration claim grants its distinct shard reward and Marks")
	support.expect(not bool(quest.claim().success), "story reward cannot be claimed twice")
	support.expect(quest.vendor_unlocked(), "claim unlocks Tala's Expedition Mark exchange")
	var catalog: Array[Dictionary] = Quest.vendor_catalog()
	support.expect(catalog.size() == 3 and catalog.map(func(offer: Dictionary) -> String: return String(offer.id)) == ["wayfinder_cache", "focused_shard", "field_supplies"], "exchange exposes three stable useful offers")
	support.expect(not bool(Quest.plan_purchase("focused_shard", 1).success) and Quest.plan_purchase("focused_shard", 1).reason == "insufficient_marks", "exchange rejects insufficient currency before mutation")
	support.expect(bool(Quest.plan_purchase("wayfinder_cache", 1).success) and int(Quest.plan_purchase("wayfinder_cache", 1).cost) == 1, "exchange returns an atomic valid purchase plan")
	var saved: Dictionary = quest.to_dictionary()
	var restored: Variant = Quest.new()
	support.expect(restored.restore(saved) and restored.to_dictionary() == saved, "claimed branch, definition, progress, and tokens round-trip through primitive state")
	var invalid := saved.duplicate(true)
	invalid["claimed_event_ids"] = ["same", "same"]
	support.expect(not restored.restore(invalid), "duplicate story event tokens are rejected on restore")

	var purge: Variant = Quest.new()
	purge.bind_island("east", forest)
	purge.accept()
	purge.record("survey_site", 2, "survey_all")
	purge.choose_branch("purge")
	purge.record("purge_site", 2, "purge_all")
	purge.record("warden_defeated", 1, "warden")
	var purge_claim: Dictionary = purge.claim()
	support.expect(bool(purge_claim.success) and purge_claim.reward.kind == "equipment" and purge_claim.reward != claimed.reward, "purge produces a different equipment payoff")
	support.expect(purge.bind_island("east", swamp) and purge.status == "offered" and purge.definition.quest_id != definition.quest_id, "replacing the island binds a fresh biome-specific story")

