extends RefCounted

const ArtAssetValidatorScript := preload("res://tools/art_asset_validator.gd")

func run(support: TestSupport) -> void:
	support.expect(FacingRules.resolve(Vector2.RIGHT) == "east", "facing rules must resolve east deterministically")
	support.expect(FacingRules.resolve(Vector2.LEFT) == "west", "facing rules must resolve west deterministically")
	support.expect(FacingRules.resolve(Vector2.UP) == "north", "facing rules must resolve north deterministically")
	support.expect(FacingRules.resolve(Vector2.DOWN) == "south", "facing rules must resolve south deterministically")
	support.expect(FacingRules.resolve(Vector2.ZERO, "north") == "north", "zero input must preserve the prior valid facing")
	support.expect(FacingRules.resolve(Vector2(1, 1), "west") == "south_east", "diagonal input must resolve to the authored southeast hero direction")
	support.expect(VisualAssetLibrary.validate_contract().is_empty(), "the registered atlas must satisfy its semantic 4x4 contract")
	support.expect(VisualAssetLibrary.asset_ids().size() == 16, "the selected bootstrap family must expose exactly sixteen semantic cells")
	support.expect(VisualAssetLibrary.region("grass") == Rect2(0, 192, 64, 64), "terrain atlas region must be stable and integer aligned")
	var valid_import := {"compress/mode": 0, "mipmaps/generate": false, "process/hdr_as_srgb": false}
	support.expect(ArtAssetValidatorScript.validate_metadata("forest_tiles.png", 256, 256, true, valid_import, 64).is_empty(), "valid pixel-art metadata must pass deterministic validation")
	var invalid_metadata := ArtAssetValidatorScript.validate_metadata("Forest Atlas.PNG", 250, 4096, false, {}, 64)
	support.expect(invalid_metadata.size() >= 5, "invalid naming, dimensions, alpha and import settings must all be diagnosed")
	var invalid_pixels := Image.create(64, 64, false, Image.FORMAT_RGBA8)
	for color_index: int in 17:
		invalid_pixels.set_pixel(color_index, 0, Color8(color_index * 13, color_index * 7, color_index * 3, 255))
	invalid_pixels.set_pixel(20, 0, Color(1, 1, 1, 0.5))
	support.expect(ArtAssetValidatorScript.validate_pixel_content("invalid.png", invalid_pixels, 64, 16).size() == 2, "pixel validator must reject both over-palette cells and semi-antialiased alpha")
	support.expect(ArtAssetValidatorScript.validate_repository().is_empty(), "registered runtime art must satisfy palette, binary-alpha and import contracts")
	var reduced := VfxSettings.new(true, 1.0)
	support.expect(is_equal_approx(reduced.shake_scale(), 0.5), "reduced effects must halve the screen-shake presentation hook")
	support.expect(is_equal_approx(VfxSettings.new(false, 5.0).intensity, 1.0), "VFX intensity must clamp to its safe maximum")
	support.expect(not reduced.secondary_details_enabled(), "reduced effects must suppress non-essential secondary details")
	support.expect(GameplayVfx.DURATIONS.size() == 8 and GameplayVfx.DURATIONS.values().all(func(value: Variant) -> bool: return float(value) <= 0.85), "all core VFX must have bounded short lifetimes")
	support.expect(LegendaryBehaviorRegistry.validate().is_empty(), "legendary definitions and runtime scripts must validate")
	var chain_definition := LegendaryBehaviorRegistry.definition("chain_mining")
	support.expect(int((chain_definition.parameters as Dictionary).maximum_targets) == 4 and is_equal_approx(float((chain_definition.parameters as Dictionary).radius), 150.0), "Chain Mining bounds must live in authored definition data")
	var bus := LegendaryEventBus.new()
	var manager := LegendaryBehaviorManager.new(bus)
	support.expect(manager.sync(["chain_mining", "chain_mining"]) and manager.active_ids() == ["chain_mining"], "duplicate legendary IDs must attach exactly once")
	support.expect(bus.resource_hit.get_connections().size() == 1, "duplicate IDs must not duplicate event subscriptions")
	var connection_count := bus.resource_hit.get_connections().size()
	support.expect(manager.sync(["chain_mining"]) and bus.resource_hit.get_connections().size() == connection_count, "idempotent equipment sync must preserve one subscription")
	var hook_counts := {"hit": 0, "critical": 0, "destroyed": 0}
	bus.hit.connect(func(_context: Dictionary) -> void: hook_counts.hit += 1)
	bus.critical_hit.connect(func(_context: Dictionary) -> void: hook_counts.critical += 1)
	bus.resource_destroyed.connect(func(_context: Dictionary) -> void: hook_counts.destroyed += 1)
	bus.emit_hit({"id": "hit"})
	bus.emit_critical_hit({"id": "critical"})
	bus.emit_resource_destroyed({"id": "resource"})
	support.expect(hook_counts == {"hit": 1, "critical": 1, "destroyed": 1}, "the shared runtime must expose hit, critical and resource-destroyed hooks")
	var effects: Array[Dictionary] = []
	bus.effect_triggered.connect(func(effect_id: String, payload: Dictionary) -> void: effects.append({"id": effect_id, "payload": payload}))
	bus.emit_resource_hit({"tick": 20, "source_damage": 8, "origin": Vector2(5, 6), "targets": [
		{"id": "a", "distance": 10.0}, {"id": "a", "distance": 11.0}, {"id": "outside", "distance": 151.0}, {"id": "c", "distance": 20.0}
	]})
	support.expect(effects.size() == 1 and String(effects[0].id) == "chain_mining", "eligible resource hit must trigger Chain Mining once")
	var chain_targets := effects[0].payload.targets as Array
	support.expect(chain_targets.size() == 2 and String(chain_targets[0].id) == "a" and String(chain_targets[1].id) == "c", "Chain Mining must remove duplicate and out-of-radius targets in stable order")
	support.expect(int(effects[0].payload.damage) == 4 and effects[0].payload.origin == Vector2(5, 6), "Chain Mining must preserve bounded power and visual origin")
	var configured_bus := LegendaryEventBus.new()
	var configured_effects: Array[Dictionary] = []
	configured_bus.effect_triggered.connect(func(effect_id: String, payload: Dictionary) -> void: configured_effects.append({"id": effect_id, "payload": payload}))
	var configured_chain: Variant = LegendaryBehaviorRegistry.create("chain_mining", {"maximum_targets": 1, "radius": 5.0, "power_multiplier": 1.0, "cooldown_ticks": 0})
	configured_chain.activate(configured_bus)
	configured_bus.emit_resource_hit({"tick": 1, "source_damage": 8, "targets": [{"id": "near", "distance": 4.0}, {"id": "far", "distance": 6.0}]})
	support.expect(configured_effects.size() == 1 and (configured_effects[0].payload.targets as Array).size() == 1 and int(configured_effects[0].payload.damage) == 8, "runtime Chain Mining must consume authored parameter overrides")
	configured_chain.deactivate()
	configured_effects.clear()
	var configured_living: Variant = LegendaryBehaviorRegistry.create("living_arrows", {"maximum_active": 1, "proc_chance": 1.0, "lifetime": 2.0})
	configured_living.activate(configured_bus)
	configured_bus.emit_hit({"weapon_type": "bow", "seed": 9, "attack_index": 1, "position": Vector2.ZERO})
	configured_bus.emit_hit({"weapon_type": "bow", "seed": 9, "attack_index": 2, "position": Vector2.ZERO})
	support.expect(configured_effects.size() == 1 and is_equal_approx(float(configured_effects[0].payload.lifetime), 2.0), "runtime Living Arrows must consume authored chance, cap and lifetime overrides")
	configured_living.deactivate()
	support.expect(manager.sync(["burning_smelter"]), "Burning Smelter must attach through the shared manager")
	var before_burning := effects.size()
	bus.emit_enemy_killed({"enemy_id": "plain", "burning": false})
	support.expect(effects.size() == before_burning, "non-burning enemies must not produce smelting value")
	bus.emit_enemy_killed({"enemy_id": "burned", "burning": true, "nearby_ores": [], "position": Vector2(8, 9)})
	support.expect(effects.size() == before_burning + 1 and int(effects.back().payload.smelting_charges) == 1, "one burning death must produce at most one bounded fallback charge")
	bus.emit_enemy_killed({"enemy_id": "burned", "burning": true, "nearby_ores": []})
	support.expect(effects.size() == before_burning + 1, "repeated death callbacks must not duplicate Burning Smelter rewards")
	support.expect(manager.sync(["living_arrows"]), "Living Arrows must attach through the same runtime")
	var living_start := effects.size()
	for index: int in 100:
		bus.emit_hit({"weapon_type": "bow", "seed": 314159, "attack_index": index, "position": Vector2(index, 0)})
	var living_count := effects.size() - living_start
	support.expect(living_count > 0 and living_count <= 3, "Living Arrows must deterministically respect its active summon cap")
	manager.clear()
	support.expect(manager.active_ids().is_empty() and bus.hit.get_connections().size() == 1, "unequip must disconnect Living Arrows while preserving unrelated hit observers")
	support.expect(not manager.sync(["unknown_effect"]) and manager.active_ids().is_empty(), "unknown effect IDs must fail safely and leave no active behavior")
